### PR TITLE
Fix #114

### LINKED ISSUE #114: Incorrect Colors in Web Demo
The web demo [incorrectly interprets](https://github.com/mooman219/fontdue/blob/gh-pages/www/index.js#L54-L56) the renderer output as being in the sRGB colorspace. `ImageData` [expects sRGB colors by default](https://chromestatus.com/feature/5807007661555712), not linear. From the fontdue docs, [`fn rasterize`](https://docs.rs/fontdue/latest/fontdue/struct.Font.html#method.rasterize) returns a coverage `Vec<u8>` where coverage is a linear scale.

### PR DESCRIPTION
**Pull request by weswigham**
Fine, why not. This is _probably_ how coverage interpreted as linear intensity maps to sRGB intensity. Maybe. My eyes have no way to tell the difference in any examples I can think of though.

Fixes #114

### CODE REVIEW

File: www/index.js [hunk 1]
```diff
@@ -46,14 +46,35 @@ function logFormatted(buffer, width, height) {
...
+function clamp(x, min, max) {
+    return x < min ? min : x > max ? max : x;
+}
+
+/**
+ * @param {number} intensity
+ */
+function linearIntensityTosRGBIntensity(intensity) {
+    const scaled = intensity / 255;
+    const converted = scaled <= 0.0031308 ? scaled * 12.92 : 1.055 * Math.pow(scaled, 1/2.4) - 0.055;
```
Comment (weswigham) [inline www/index.js:64]: 🤷‍♀️
